current_version: "5.21.2"
base_branch: "master"
strategy:
  name: "semver"
  part: "patch"
commit:
  author: "foo <bar>"
tag:
  apply: False
  format: "v{version}"
auto_remote_push: False # or False
tracked_files:
  - src/clipper/version.py
  - .github/workflows/yt_clipper_ci.yml
  - src/markup/yt_clipper.ts
  - pyproject.toml
