
// const ytclipperSelectors = {
//   playerContainer: 'div[id=ytc-media-player-container]',
//   player: 'media-player',
//   playerClickZone: 'div[id=ytc-media-player-container]',
//   videoContainer: 'div[id=ytc-media-player-container]',
//   video: 'video',
//   progressBar: 'media-time-slider',
//   markersDiv: 'media-controls > media-controls-group:nth-of-type(3)',
//   markerNumberingsDiv: 'media-controls > media-controls-group:nth-of-type(3)',
//   theaterModeIndicator: 'placeholder',
//   settingsEditor: '#ytc-editor',
//   settingsEditorTheater: '#ytc-editor',
//   shortcutsTable: '#ytc-editor',
//   frameCapturerProgressBar: '#ytc-editor',
//   flashMessage: '#ytc-editor',
//   cropOverlay: 'div[id=ytc-media-player-container]',
//   cropMouseManipulation: 'div[id=ytc-media-player-container]',
//   speedChartContainer: 'div[id=ytc-media-player-container]',
//   cropChartContainer: '#ytc-editor',
//   controls: '#media-controls',
//   controlsGradient: '#media-controls',
//   shortcutsTableButton: 'media-menu-button',
// };
