#!/bin/bash
cd "$(dirname "$0")"

./yt_clipper -h

read -p "First enter the paths of 1 or more markers json data files (you may be able to drag and drop files at the prompt): " JSONPROMPT

IFS=$'\n' JSONS=( $(xargs -n1 <<< "$JSONPROMPT") )

read -p "Next provide any additional options: " OPTS

for JSON in "${JSONS[@]}"
do
  if [ -f "$JSON" ]; then
    ./yt_clipper --markers-json "$JSON" "$OPTS"
  else 
    echo "$JSON does not exist"
  fi
done