#!/bin/bash
cd "$(dirname "$0")" || exit

echo "----------------------------------------------------"
echo "This script preprocesses hevc (h265) input video to ensure that it is compatible with ffmpeg."
echo "Currently, the steps performed are a 1) Convert HEVC/H.265 bitstream from length-prefixed mode to start-code-prefixed mode."
echo "The output file will be suffixed with '-preproc'."
echo "----------------------------------------------------"

read -rp "Enter the path of a video file that you would like to trim (you may be able to drag and drop files at the prompt): " VIDEOSPROMPT

IFS=$'\n' VIDEOS=($(xargs -n1 <<<"$VIDEOSPROMPT"))

NVIDEOS="${#VIDEOS[@]}"

if [ "$NVIDEOS" -ne 1 ]; then
  echo "Provide a single video file as input."
  exit
fi

VIDEO="${VIDEOS[0]}"

DIR="$(dirname "$VIDEO")"
NAME="${VIDEO##*/}"
EXT=".${NAME##*.}"
NAME="${NAME%.*}"
OUT="$DIR/$NAME-trim$EXT"

if [ -f "$VIDEO" ]; then
  echo "generating $OUT..."
  ./bin/ffmpeg -i "$VIDEO" -c copy -bsf:v hevc_mp4toannexb "$OUT"
else
  echo "$VIDEO does not exist."
fi

echo "----------------------------------------------------"
echo "This script preprocesses hevc (h265) input video to ensure that it is compatible with ffmpeg."
echo "Currently, the steps performed are a 1) Convert HEVC/H.265 bitstream from length-prefixed mode to start-code-prefixed mode."
echo "The output file will be suffixed with '-preproc'."
echo "----------------------------------------------------"
